package restore

import (
	"fmt"
	"strings"

	"github.com/akvartz/loadout/internal/state"
)

type Brewfile struct{}

func NewBrewfile() *Brewfile { return &Brewfile{} }

func (bf *Brewfile) Name() string { return "brewfile" }

func (bf *Brewfile) Generate(st state.State) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by loadout\n\n")

	if pkgs := st.Sources["brew"].Packages; len(pkgs) > 0 {
		for _, p := range pkgs {
			fmt.Fprintf(&b, "brew %q\n", p)
		}
		b.WriteString("\n")
	}

	unsupported := []string{"apt", "flatpak", "snap", "pip", "cargo", "npm", "appimage", "nix"}
	for _, src := range unsupported {
		pkgs := st.Sources[src].Packages
		if len(pkgs) == 0 {
			continue
		}
		fmt.Fprintf(&b, "# %s packages (no Brewfile equivalent — install manually):\n", src)
		for _, p := range pkgs {
			fmt.Fprintf(&b, "#   %s\n", p)
		}
		b.WriteString("\n")
	}

	return b.String(), nil
}
