package restore

import (
	"testing"

	"github.com/akvartz/loadout/internal/state"
)

func TestBrewfile_Name(t *testing.T) {
	bf := NewBrewfile()
	if got := bf.Name(); got != "brewfile" {
		t.Errorf("Name() = %v, want %v", got, "brewfile")
	}
}

func TestBrewfile_Generate(t *testing.T) {
	tests := []struct {
		name    string
		state   state.State
		want    string
		wantErr bool
	}{
		{
			name:  "empty state",
			state: stateWith(nil),
			want:  "# Generated by loadout\n\n",
		},
		{
			name: "only brew packages",
			state: stateWith(map[string][]string{
				"brew": {"fd", "ripgrep"},
			}),
			want: "# Generated by loadout\n\nbrew \"fd\"\nbrew \"ripgrep\"\n\n",
		},
		{
			name: "only cask packages",
			state: stateWith(map[string][]string{
				"brew-cask": {"firefox", "google-chrome"},
			}),
			want: "# Generated by loadout\n\ncask \"firefox\"\ncask \"google-chrome\"\n\n",
		},
		{
			name: "brew and cask packages",
			state: stateWith(map[string][]string{
				"brew":      {"git"},
				"brew-cask": {"slack"},
			}),
			want: "# Generated by loadout\n\nbrew \"git\"\n\ncask \"slack\"\n\n",
		},
		{
			name: "unsupported packages",
			state: stateWith(map[string][]string{
				"apt": {"curl", "wget"},
				"npm": {"prettier"},
			}),
			want: "# Generated by loadout\n\n" +
				"# apt packages (no Brewfile equivalent \xe2\x80\x94 install manually):\n" +
				"#   curl\n" +
				"#   wget\n\n" +
				"# npm packages (no Brewfile equivalent \xe2\x80\x94 install manually):\n" +
				"#   prettier\n\n",
		},
		{
			name: "mixed supported and unsupported packages",
			state: stateWith(map[string][]string{
				"brew":      {"tmux"},
				"brew-cask": {"iterm2"},
				"cargo":     {"bat"},
			}),
			want: "# Generated by loadout\n\n" +
				"brew \"tmux\"\n\n" +
				"cask \"iterm2\"\n\n" +
				"# cargo packages (no Brewfile equivalent \xe2\x80\x94 install manually):\n" +
				"#   bat\n\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			bf := NewBrewfile()
			got, err := bf.Generate(tt.state)
			if (err != nil) != tt.wantErr {
				t.Errorf("Generate() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("Generate() got:\n%s\nwant:\n%s", got, tt.want)
			}
		})
	}
}
