package restore

import (
	"fmt"
	"strings"

	"github.com/akvartz/loadout/internal/state"
)

type Nix struct{}

func NewNix() *Nix { return &Nix{} }

func (n *Nix) Name() string { return "nix" }

func (n *Nix) Generate(st state.State) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by loadout — paste into home-manager home.nix\n")
	b.WriteString("# WARNING: nix attribute names may differ from nix-env package names.\n")
	b.WriteString("# Verify each package name against https://search.nixos.org\n\n")
	b.WriteString("home.packages = with pkgs; [\n")

	if pkgs := st.Sources["nix"].Packages; len(pkgs) > 0 {
		for _, p := range pkgs {
			fmt.Fprintf(&b, "  %s\n", p)
		}
	} else {
		b.WriteString("  # no nix-managed packages found in snapshot\n")
	}

	b.WriteString("];\n\n")

	unsupported := []string{"apt", "flatpak", "snap", "pip", "cargo", "npm", "brew", "appimage"}
	for _, src := range unsupported {
		pkgs := st.Sources[src].Packages
		if len(pkgs) == 0 {
			continue
		}
		fmt.Fprintf(&b, "# %s packages (add nix equivalents manually):\n", src)
		for _, p := range pkgs {
			fmt.Fprintf(&b, "#   %s\n", p)
		}
		b.WriteString("\n")
	}

	return b.String(), nil
}
